zkBob/zkbob-contracts

foundry.toml, src/interfaces/IERC20Permit.sol, src/token/ERC20Permit.sol, src/utils/EIP712.sol, src/zkbob/utils/ZkBobAccounting.sol, src/zkbob/verifiers/prodV1/TransferVerifier.sol, src/zkbob/verifiers/prodV1/TreeUpdateVerifier.sol, src/zkbob/verifiers/stageV1/TransferVerifier.sol, src/zkbob/verifiers/stageV1/TreeUpdateVerifier.sol, test/BobToken.t.sol
Fix permit behaviour in case of sudden chain id change, i.e. due to a hardfork.
=> Secure handling of chainid in EIP712 domains

src/zkbob/ZkBobPool.sol, src/zkbob/utils/ZkBobAccounting.sol, test/mocks/ZkBobAccountingMock.sol, test/zkbob/ZkBobPool.t.sol, test/zkbob/utils/ZkBobAccounting.t.sol
This PR introduces 256 dynamic pool limit tiers, configurable by the pool owner.
* `0` - is the default pool limits tier, assigned to any unknown user.
* `1-254` - are pool limits that might be assigned by the owner to well-known users with sufficient off-chain KYC requirements.
* `255` - pool limits tier, that completely prohibits interaction with the pool from the specified address.
Pool limits for specific tier could be set/updated by calling the `setLimits(...)` function.
Users tiers could be updated by calling the `setUsersTiers(...)` function.
As it now becomes possible for different users to have different limits, `getLimitsFor(...)` function might returns usage values higher than specific limits of the particular lower tier user.
It might be now the case, that during high …
=> Multiple configurable pool limit tiers

.gitmodules, foundry.toml, script/scripts/BobSeller.s.sol, script/scripts/BobToken.s.sol, script/scripts/Env.s.sol, script/scripts/Local.s.sol, src/interfaces/ITokenSeller.sol, src/utils/Sacrifice.sol, src/utils/UniswapV3Seller.sol, src/zkbob/ZkBobPool.sol, test/BobToken.t.sol, test/shared/Env.t.sol, test/zkbob/ZkBobPool.t.sol
When withdrawing BOB from the zkBOB pool to an empty account, user may optionally ask to convert a fraction of the withdrawn amount to native coins (ETH/MATIC).
Amount of BOB converted to ETH/MATIC and sent to the user is denoted by `native_amount` value in memo.
On-chain Uniswap operation can be subject to unexpected slippage, so users are discouraged from making large ETH/MATIC withdrawals by using this mechanism. The contract does not enforce any hard limit on the withdrawn amount, but UI will contain a soft upper limit.
In order to prevent possible abuse of the relayer, the contract will not revert in case user specified address can't accept ETH/MATIC, in this case selfdestruct opcode will be used to force-send the obtained ETH/MATIC to the user.
1. Deploy `ZkBobPool` contract …
=> Support MATIC withdrawals from selling BOB on Uniswap

src/interfaces/ILendingPool.sol, src/yield/AAVEYieldImplementation.sol, test/BobVault.t.sol, test/shared/Env.t.sol, test/zkbob/ZkBobPool.t.sol
AAVE V3 uses the same interface as AAVE V2 for all external operations, so it should be pretty straightforward to integrate either of them in BobVault.
Additional fork tests also ensure proper functioning of the lending integration in across multiple AAVE markets in different chains.
=> Add tests for AAVE V3 integration

script/scripts/Env.s.sol, script/scripts/Local.s.sol, script/scripts/ZkBobPool.s.sol
Add explicitly configurable pool id for future deployments. In order to avoid accidental replay attacks, future deployments should use a different pool id from the Polygon zkBob pool (e.g. new Goerli staging deployment).
=> Configurable pool id for deployment scripts

script/scripts/Env.s.sol, script/scripts/NewZkBobPoolImpl.s.sol, src/zkbob/ZkBobPool.sol, src/zkbob/utils/ZkBobAccounting.sol, test/zkbob/utils/ZkBobAccounting.t.sol
The current codebase contains a bug that prevents proper daily deposit/withdrawal limit reset during a new day transition:
1. When the new day starts with a deposit operation, only daily deposit limit would be reset
2. When the new day starts with a withdrawal operation, only daily withdrawal limit would be reset
3. When the new day starts with a transfer operation, none of the daily limits would be reset
This PR fixes that and adds a regression test.
=> Fix daily limits reset

src/token/ERC20Recovery.sol
The `executeRecovery` function in `ERC20Recovery` can only be called by the owner or the recovery admin. When recovering the tokens, they are transferred to the `recoveredFundsReceiver` address. If this address is a contract, the `onTokenTransfer` function is called. This call could be used to reenter the `executeRecovery` function in order to double-claim the funds to recover. This would allow the recovery admin or the owner to exceed the intended `recoveryLimit`.
_Comments to changes:_
The order of storage writings for recovery execution flow was changes, so that the are now executed before respected receiver callback.
=> Fix executeRecovery re-entrancy

src/zkbob/ZkBobPool.sol, src/zkbob/manager/MutableOperatorManager.sol, src/zkbob/utils/ZkBobAccounting.sol
Many state-changing operations do not emit events. Consider emitting events for important state
changes.
These operations include:
`ZkBobPool`:
- `initialize()`
- `setTokenSeller()`
- `setOperatorManager()`
`ZkBobAccounting`:
- `_setLimits()`
- `_resetDailyLimits()`
- `_setUsersTier()`
`BobVault:`
- `setYieldAdmin()`
- `setInvestAdmin()`
`MutableOperatorManager`:
- `_setOperator()`
`ERC20Recovery`:
- `setRecoveryAdmin()`
- `setRecoveredFundsReceiver()`
- `setRecoveryLimitPercent()`
- `setRecoveryRequestTimelockPeriod()`
`Claimable`:
- `setClaimingAdmin()`
_Comments to changes:_
Event describing the corresponding changes were added to:
- `ZkBobPool`: `setTokenSeller()`, `setOperatorManager()`, `withdrawFee()`
- `ZkBobAccounting`: `_setLimits()`
- `MutableOperatorManager`: `_setOperator()` …
=> Emit missing events on important configuration changes

src/BobVault.sol, test/BobVault.t.sol
BobVault implementation contract contains several delegate-calls to addresses configured by owner, thus keeping a non-zero owner address in the implementation contract is not safe, as the owner can execute a delegated self-destruct.
The safest option would be to renounce ownership of the implementation contract in the constructor.
=> Renounce BobVault implementation ownership in constructor

src/BobVault.sol
The BobVault contract should not use any tokens with reentrant transfers, such as an ERC777 token, as collateral. This could lead to inconsistent event orderings or potentially more severe issues.
=> Added comment to not use tokens with reentrant transfers

src/zkbob/ZkBobPool.sol, test/zkbob/ZkBobPool.t.sol
For the deposit transactions, there is an unlikely case with relayer fee being larger than deposited amount.
Such transactions don't make any sense for the signing user, cannot be generated via UI and SDK, but introduce unnecessary confusion, as highlighted during the audit.
This PR replaces deposit amounts validation checks with a stricter alternative, which also ensures that deposit fee is lower than deposit amount.
=> Forbid deposit transactions with negative token delta

src/BobVault.sol, src/zkbob/utils/ZkBobAccounting.sol, test/zkbob/utils/ZkBobAccounting.t.sol
There are some places in the code with missing overflow checks on uint downcasting to smaller bit sizes. Although it seems impossible to observe such values in practice, it makes sense to add missing overflow sanity checks.
=> Add sanity checks on uint conversion limits

src/interfaces/IERC20Permit.sol, src/token/ERC20Permit.sol, src/zkbob/utils/CustomABIDecoder.sol, test/BobToken.t.sol
The `ZkBobPool` permittable deposit relies on the `ERC20Permit.receiveWithSaltedPermit` function. However, the signature used in this function can be used in the `ERC20Permit.saltedPermit` function as well. An attacker can intercept the deposit transaction, extract the signature and use it in the call to `saltedPermit`. As a result of this action, the permittable deposit will fail due to the nonce already having been used.
In regular use-cases for permit, a typical fallback would work perfectly fine. However, in case of `ZkBobPool` permittable deposit processing, extra logic assigned for salt signature validation (which was the original reason behind introducing salted permits) prevents us from implementing such kind of fallback.
The simplest solution would be to remove regular …
=> Fix permit-related issues

src/BobVault.sol
The token buffer, dust and yield fields are updated after the external call. If the yield contract has a reentrancy point, where BobVault can be called again - this update can happen in an invalid state. The external calls should happen after all the state variable updates.
=> Fix state writing order

src/utils/UniswapV3Seller.sol
When the withdrawal with native_amount is submitted to the ZkBobPool, the sale of tokens for ETH happens using the UniswapV3Seller contract. However, the amountOutMinimum parameter of this swap is 0. A potential attacker can place orders that would manipulate the price, forcing the sellForETH trade to be executed with a bad price. Thus, due to the lack of spread control, any use of UniswapV3Seller can result in a bad trade, allowing price manipulators to pocket the profit from this trade.
_Comments to changes:_
This feature is only intended to swap small amounts of tokens, purely for funding wallets with gas tokens. UI will strongly dissuade users for doing swaps that are larger than e.g. 100$ in value.
Added a warning comment to the sellForETH function.
=> Add warning comment for possible sellForETH slippage

script/scripts/BobVault.s.sol, src/BobVault.sol, test/BobVault.t.sol
After some usage of BobVault in production, necessity in few more limits appeared
* Add `maxBalance` per-collateral configuration, which describes max amount of backing collateral (without accounting for fees). `buy` and `swap` operations will revert if such limit is exceeded. Previously, an implicit constant limit of `type(uint128).max` was used for all collaterals.
* Add `maxInvested` per-collateral configuration, which describes max amount of tokens that could be invested into the yield bearing protocol. This configuration only impacts calls to `invest` and restricts invested amount if necessary.
=> Add per-collateral limits to BobVault

.github/workflows/contract_diff.yml
Add manual CI action for evaluating diff between deployed contract and another deployed contract or its local sources:
Examples:
```bash
gh workflow run contract_diff --ref feat/diff-action \
-f chain=polygon \
-f target_contract_address=0x525b4E120dDC602fF055Aa86803acD7D71F0c753 \
-f etherscan_api_key=$API_KEY \
-f source=source_code \
-f ref=1.0.0-rc0
gh workflow run contract_diff --ref feat/diff-action \
-f chain=polygon \
-f target_contract_address=0x525b4E120dDC602fF055Aa86803acD7D71F0c753 \
-f source_contract_address=0x98DB3A72BeF2145A8F8d8B94F81317341Af2b08C \
-f etherscan_api_key=$API_KEY \
-f source=contract
```
=> CI action for obtaining contracts diff

src/zkbob/utils/KycProvidersManagerStorage.sol, src/zkbob/utils/ZkBobAccounting.sol, test/zkbob/utils/ZkBobAccounting.t.sol
This approach was chosen to avoid storage slots re-arrangement that could happen after upgrade to the new implementation of zkBOB pool.
It suggests to dedicate the slot `0x06c991646992b7f0f3fd0c832eac3f519e26682bcb82fbbcfd1ff8013d876f64` to keep the KYC Providers Manager contract address.
=> Explicit storage slot to keep KycProvidersManager

src/interfaces/IBurnableERC20.sol, src/token/ERC20MintBurn.sol, test/BobToken.t.sol
After some additional research within potential bridge integrations and other minting mechanics (see #27 #29), it became clear that `burnFrom` function will be a more convenient alternative, will generate cleaner history, and will be cheaper gas-wise.
=> Add burnFrom burning function

src/BobVault.sol, src/minters/BalancedMinter.sol, src/minters/BaseMinter.sol, src/minters/FlashMinter.sol, src/minters/SurplusMinter.sol, src/token/BaseERC20.sol, src/token/ERC20Recovery.sol, src/utils/UniswapV3Seller.sol, src/zkbob/ZkBobDirectDepositQueue.sol, src/zkbob/ZkBobPool.sol, src/zkbob/utils/ZkBobAccounting.sol, test/BobVault.t.sol, test/minters/BalancedMinter.t.sol
Incorporate minor suggestions and optimizations from the recent audit
=> Audit suggestions

src/zkbob/ZkBobPool.sol, src/zkbob/utils/ZkBobAccounting.sol, test/zkbob/ZkBobPool.t.sol
This PR fixes two minor problems identified within the accounting module:
1. Incorrect accounting of private transfer fees, i.e. mistakenly assigning them to the limits tier of `address(0)`.
2. Missing stats counter adjustments within processing of direct deposit batches (e.g. adjustments to the cumulative TVL and internal snapshots).
=> Fix issues with stats counters

script/scripts/DeployZkBobPoolModules.s.sol, src/interfaces/IZkBobAccounting.sol, src/interfaces/IZkBobPool.sol, src/zkbob/ZkBobPool.sol, src/zkbob/utils/ZkBobAccounting.sol, test/interfaces/IZkBobPoolAdmin.sol, test/zkbob/ZkBobPool.t.sol
Add forced exit functionality that allows any user for withdraw funds from the pool in case of an emergency(e.g. prolonged sequencer outage).
Forced exits can be submitted directly to the smart contract, bypassing the relayer, by generating a valid withdrawal proof. Forced exited accounts cannot be further used or recovered, accumulated energy of forced exited account is being forfeited during the exit.
=> Add forced exit

src/zkbob/ZkBobPool.sol, test/interfaces/IZkBobPoolAdmin.sol, test/zkbob/ZkBobPool.t.sol
Previous implementation contained a bug, allowing anyone to infinitely resubmit the same forced exit proof again and again, effectively preventing exiting party from ever finalizing the withdrawal.
One way to fix that - disallow forced exit submission for nullifiers for which forced exists already exist. However, in order for exiting party to still be able to re-submit their forced exit after 24 hours, extra cancellation method is needed.
=> Fix forced exit re-use
